### ISSUE TITLE
Converting string including two spaces in a row crashes.

### ISSUE THREAD

**Issue by acomagu** [mesqueeb/case-anything#1]
Crashes:

```javascript
pascalCase('a  b');
```

**Comment by mesqueeb** [comment]
@acomagu thanks for your ticket!!
I fixed it in the latest version! (v1.0.2)

<sub>--<br>case-anything was made with ♥ by Luca Ban.<br>If you use this library in your projects, you can support the maintenance of this library by a small <a href="https://github.com/sponsors/mesqueeb">contribution via Github 💜</a>.<br>You can also reach out <a href="https://twitter.com/mesqueeb">on twitter</a> if you want a one-on-one coding review/lesson. 🦜</sub>
