### ISSUE TITLE
feat: add train case

### ISSUE THREAD

**Issue by thim81** [mesqueeb/case-anything#10]
The request "header" keys are typically set as kebab-case but with the first letters as in capital.

See the Postman screenshot:

![2021-12-28 at 21 37 18@2x](https://user-images.githubusercontent.com/952446/147605265-b84259dc-2383-4813-96cc-a2e16c4afa2d.png)

The normal "kebab-case" transforms the full string to lowercase.
To facilitate the automatic casing of header keys, it want to get your input if you would be open for a PR to introduce an additional casing: `Capital-Kebab-Case`?

```js
/**
 * converts strings to Capital-Kebab-Case
 *
 * @export
 * @param {string} string
 * @returns {string} in Kebab-Case
 */
function capitalKebabCase(string) {
    return getParts(string, noSpecialChars)
        .map(part => capitaliseWord(part))
        .join('-')
}
```

Example:
`capitalKebabCase('ponytaVaporeonPOLIWRATH_ButterfreeA')` => `Ponyta-Vaporeon-Poliwrath-Butterfree-A`

Any feedback on the idea is welcome.

**Comment by mesqueeb** [comment]
@thim81 this is an easy one for me to add yeah. Let's add it. The library is tree-shakable anyway so there's no cost in adding this.

I wonder if there's a better name though. Is "capital kebab case" the best name?

Doesn't this kind of casing have some sort of name? Can you do some research on this?
I feel like if it's a long-used convention there must be some specific name for it somewhere! : D

**Comment by thim81** [comment]
For the naming, if I browse the internet I've come across the following names:
- kebab-case with uppercase
- Hyphenated-Pascal-Case

I ll look some further...

**Comment by thim81** [comment]
@mesqueeb 
I think we have a winner "Train-Case", see https://medium.com/nerd-for-tech/programming-case-types-explained-143cad3681e3 and https://stackoverflow.com/a/64293621/7157530 and https://github.com/jawira/case-converter and https://en.wikipedia.org/wiki/Naming_convention_(programming)

<img width="484" alt="2021-12-29 at 09 44 52@2x" src="https://user-images.githubusercontent.com/952446/147643615-b98313da-5a7f-488b-9f51-c151c07d0ce0.png">

FYI: The `Ada case`, `Macro case`, `Sentence case` might be interesting to review as additional casing options?

**Comment by mesqueeb** [comment]
@thim81 Train Case is awesome : D
You can update your PR and I will release it.

Feel free to make other PR's for Ada case and Cobol case and Dot notation.

Macro case we already have but I call it Const Case. : )

Sentence case doesn't really make sense to me, so let's leave it out for now.
